#!/bin/bash
#
# Copyright 2012, Brian Smith
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

JOBID=$1

if [ -z "$JOBID" ]; then
	echo "Need a jobid as an argument!"
	exit 1
fi

for pid in $(ls /proc | egrep '[0-9]+'); do
	[ -f "/proc/$pid/environ" ] || continue
    grep -q "JOB_ID=$JOBID" /proc/$pid/environ && pids="$pids,$pid"
done 

pids=$(echo $pids | sed 's/^\,//g')
if [ -z "$pids" ]; then
    echo "No PIDs of job $JOBID live here."
    exit
fi

top -n 1 -b -M -p $pids | egrep '^[ ]*[0-9]+[ ]+[a-z0-9]+' | awk '{ printf "%8s %8s %8s %8s %6s %6s %12s  %s\n", $1, $5, $6, $7, $9, $10, $11, $12 }'
