#!/bin/bash
#
#___INFO__MARK_BEGIN__
##########################################################################
#
#  The Contents of this file are made available subject to the terms of
#  the Sun Industry Standards Source License Version 1.2
#
#  Sun Microsystems Inc., March, 2001
#
#
#  Sun Industry Standards Source License Version 1.2
#  =================================================
#  The contents of this file are subject to the Sun Industry Standards
#  Source License Version 1.2 (the "License"); You may not use this file
#  except in compliance with the License. You may obtain a copy of the
#  License at http://gridengine.sunsource.net/Gridengine_SISSL_license.html
#
#  Software provided under this License is provided on an "AS IS" basis,
#  WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING,
#  WITHOUT LIMITATION, WARRANTIES THAT THE SOFTWARE IS FREE OF DEFECTS,
#  MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE, OR NON-INFRINGING.
#  See the License for the specific provisions governing your rights and
#  obligations concerning the Software.
#
#  The Initial Developer of the Original Code is: Sun Microsystems, Inc.
#
#  Copyright: 2001 by Sun Microsystems, Inc.
#
#  All Rights Reserved.
#
##########################################################################
#___INFO__MARK_END__

#
# Start the mpd in a loop. On the master node grep the granted portnumber
# with mpdtrace -l
#

if [ -z "$JOB_ID" ]; then
    echo "mpdbood must be run from inside a job!"
    exit 1
fi

export MPD_CON_EXT="sge_$JOB_ID.$SGE_TASK_ID"
NODE=`hostname | cut -d'.' -f 1`

for host in `cat $TMPDIR/machines.mpich2`; do
    host=${host%:*}
    if [ "$host" == "$NODE" ]; then
        %%INSTALL_DIR%%/mpd/bin/$ARCH/start_mpd -n $host `which mpd`
        actual_retry=1
        while [ $actual_retry -le $RETRIES ] ; do
            mpdtrace -l &> /dev/null && break
            sleep $SLEEPTIME
            ((actual_retry += 1))
        done
        if [ -z "$MASTER" ]; then
            echo "$me: local mpd could not be started, aborting"
            exit 0
        fi
    
        PORT=`expr "$MASTER" : ".*_\([0-9]*\)"`
    else
        %%INSTALL_DIR%%/bin/$ARC/start_mpd -n $host `which mpd` $NODE $PORT
    fi
done

actual_retry=1
while [ $actual_retry -le $RETRIES ] ; do
    numhosts=`mpdtrace | wc -l`

    [ $NHOSTS -eq ${numhosts:-0} ] && exit 0
    sleep $SLEEPTIME
    ((actual_retry += 1))
done
